# GitLab Runner Helm Chart values.yaml

## The GitLab Server URL (with http/https) and Registration Token
gitlabUrl: https://gitlab.basile.local/
runnerRegistrationToken: "glrt-t1_aFmzZiW6P-uvMERhPjKU"

## RBAC for the GitLab Runner
rbac:
  create: true
  rules: []

serviceAccount:
  create: true
  name: gitlab-runner

## Runner configuration
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "alpine:3.21"
  tags: "kubernetes,cluster"
  runUntagged: true
  protected: false
  executor: kubernetes
  
  # Kubernetes executor specific configuration
  kubernetes:
    image: alpine:3.21
    namespace: "gitlab-runner"
    privileged: true
    serviceAccount: gitlab-runner
    resources:
      requests:
        cpu: "300m"
        memory: "300Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"

# Persistent storage for cache
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
