---
- name: Deploy high-availability pods using kubectl
  kubernetes.core.k8s:
    state: present
    kubeconfig: "~/.kube/config"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app-deployment-production
        namespace: "{{ CI_ENVIRONMENT_SLUG }}"
      spec:
        replicas: 3  # High availability with multiple replicas
        revisionHistoryLimit: 0
        selector:
          matchLabels:
            app: microservice
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
        template:
          metadata:
            labels:
              app: microservice
          spec:
            containers:
              - name: app-container-{{ CI_ENVIRONMENT_SLUG }}
                image: "{{ CI_REGISTRY_IMAGE }}:{{ TAG }}"
                imagePullPolicy: Always
                command: ["/bin/sh", "-c"]
                args: ["python -m addrservice.tornado.server --port 8080 --config ./configs/addressbook-local.yaml --debug"]  # Custom command to start the pod
                ports:
                  - containerPort: 8080
                resources:
                  limits:
                    cpu: "500m"
                    memory: "512Mi"
                  requests:
                    cpu: "200m"
                    memory: "256Mi"
            imagePullSecrets:
              - name: gitlab-registry-credentials
