---
# tasks file for docker

- name: Import config task
  ansible.builtin.import_tasks: config.yml
  tags: integration, preproduction, production, review

- name: Import deploy task
  ansible.builtin.import_tasks: deploy.yml
  tags: preproduction, integration, review

- name: Import deploy production task
  ansible.builtin.import_tasks: deploy_production.yml
  tags: production

- name: Import ingress task
  ansible.builtin.import_tasks: ingress.yml
  tags: preproduction, integration, review

- name: Import ingress production task
  ansible.builtin.import_tasks: ingress_production.yml
  tags: production

- name: Import service task
  ansible.builtin.import_tasks: service.yml
  tags: integration, preproduction, production, review
