---
# tasks file for docker

- name: Create temporary kubeconfig directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0700'

- name: Copy admin.conf to kubeconfig
  copy:
    src: "admin.conf"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    mode: '0600'

- name: Deploy high-availability pods using kubectl
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app-deployment
        namespace: default
      spec:
        replicas: 3  # High availability with multiple replicas
        selector:
          matchLabels:
            app: microservice
        template:
          metadata:
            labels:
              app: microservice
          spec:
            containers:
            - name: app-container
              image: "{{ CI_REGISTRY_IMAGE }}"
              imagePullPolicy: Always
              command: ["/bin/sh", "-c"]
              args: ["python addrservice/tornado/server.py --port 8080 --config ./configs/addressbook-local.yaml --debug"]  # Custom command to start the pod
              ports:
              - containerPort: 8080
              resources:
                limits:
                  cpu: "500m"
                  memory: "512Mi"
                requests:
                  cpu: "200m"
                  memory: "256Mi"

- name: Create service for the deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: microservice-service
        namespace: default
      spec:
        type: ClusterIP
        selector:
          app: microservice
        ports:
        - port: 80
          targetPort: 8080
