---
# tasks file for docker

- name: Import config task
  ansible.builtin.import_tasks: config.yml

- name: Import deploy task
  ansible.builtin.import_tasks: deploy.yml

- name: Import service task
  ansible.builtin.import_tasks: service.yml
