---
- name: Create Service for the application
  kubernetes.core.k8s:
    state: present
    kubeconfig: "~/.kube/config"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: app-service
        namespace: "{{ CI_ENVIRONMENT_SLUG }}"
      spec:
        selector:
          app: microservice
        ports:
          - port: 80
            targetPort: 8080
        type: ClusterIP
