---
ansible_python_interpreter: /usr/bin/python3.12

CI_REGISTRY: "{{ lookup('env', 'CI_REGISTRY') }}"
CI_REGISTRY_USER: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
CI_REGISTRY_PASSWORD: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
CI_REGISTRY_IMAGE: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}"
CI_ENVIRONMENT_SLUG: "{{ lookup('env', 'CI_ENVIRONMENT_SLUG') }}"
BASE64_SSL_CERTIFICATE: "{{ lookup('env', 'BASE64_SSL_CERTIFICATE') }}"

TAG: "{{ lookup('env', 'TAG') }}"

CERTIFICATE_AUTHORITY_DATA: "{{ lookup('env', 'CERTIFICATE_AUTHORITY_DATA') }}"
CLIENT_CERTIFICATE_DATA: "{{ lookup('env', 'CLIENT_CERTIFICATE_DATA') }}"
CLIENT_KEY_DATA: "{{ lookup('env', 'CLIENT_KEY_DATA') }}"
HOST: "{{ lookup ('env', 'HOST') }}"
KUBE_DOMAIN: "{{ lookup('env', 'KUBE_DOMAIN') }}"
