build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    TAG: $CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'
      variables:  
        TAG: $CI_COMMIT_TAG
  before_script:
    - echo "${SSL_CERTIFICATE}" >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/.gitlab/docker/python/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${TAG}"

build-ansible-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    TAG: ansible-$CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BEFORE_SHA'
      changes:
        - .gitlab/docker/ansible/Dockerfile
    - if: '$CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "push"'
      changes:
        - .gitlab/docker/ansible/Dockerfile
      variables:  
        TAG: ansible-$CI_COMMIT_TAG
  before_script:
    - echo "${SSL_CERTIFICATE}" >> /kaniko/ssl/certs/ca-certificates.crt
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/.gitlab/docker/ansible/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${TAG}"
